# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COVID Lens' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftKeychainWrapper', '~> 4.0'
  # Pods for COVID Lens
  # Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.34.0'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleSignIn'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  
  target 'COVID LensTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |bc|
        if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
          bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end

end
