# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'COVID Lens' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for COVID Lens
  # Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleSignIn'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'COVID LensTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'COVID LensUITests' do
    # Pods for testing
  end

end
